# Generated by Django 4.2.1 on 2023-05-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'translation',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=200)),
                ('word_type', models.CharField(choices=[('n', 'noun'), ('v', 'verb'), ('adj', 'adjective'), ('adv', 'adverb'), ('con', 'conjunction'), ('other', 'other')], default='other', max_length=20)),
                ('date_added', models.DateTimeField()),
                ('translations', models.ManyToManyField(through='dictionary.Translation', to='dictionary.word')),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='source_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_word', to='dictionary.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='target_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_word', to='dictionary.word'),
        ),
    ]
