# Generated by Django 4.2.1 on 2023-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(default='', max_length=300),
        ),
    ]
