# Generated by Django 4.2.1 on 2023-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
