# Generated by Django 4.2.1 on 2023-07-05 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_word_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_practiced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='mistakes',
            field=models.IntegerField(default=0),
        ),
    ]
