# Generated by Django 4.2.1 on 2023-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_word_last_practiced_word_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
