# Generated by Django 4.2.1 on 2023-07-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_word_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(default='na', max_length=2),
        ),
    ]
